DROP DATABASE IF EXISTS dwh;
CREATE DATABASE dwh;

DROP USER IF EXISTS dwh_owner;
CREATE USER dwh_owner PASSWORD 'dwh_owner' SUPERUSER;

\c dwh;

CREATE SCHEMA dwh AUTHORIZATION dwh_owner;
CREATE SCHEMA staging AUTHORIZATION dwh_owner;

GRANT ALL PRIVILEGES ON SCHEMA dwh TO dwh_owner;
GRANT ALL PRIVILEGES ON SCHEMA staging TO dwh_owner;

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA dwh TO dwh_owner;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA staging TO dwh_owner;

